### PR TITLE
should fix version problem

### LINKED ISSUE #86: Adapter version not displaying in Meshery UI
#### Current Behavior
Screen Shot 2022-01-11 at 5 01 51 PM

#### Expected Behavior
The release tag (version) should be displayed in this tooltip.

#### Environment

- **Host OS:** Mac
- **Platform:**  Kubernetes
- **Meshery Server Version:** stable-v0.6.0-rc-3
- **Meshery Client Version:** stable-v0.6.0-rc-3
- **Meshery Adapter Version:** ???

Container image digest: sha256:93c2291e83e86d69d9c0838a81b6373cae005910be7298aac65fa2696aa8112d

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by warunicorn19**
Signed-off-by: Aditya Chatterjee <speak2adi@gmail.com>

**Description**
Should fix the issue getting version on UI.
This PR fixes #86 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -90,6 +92,8 @@ func main() {
 	service.Handler = handler
 	service.Channel = make(chan interface{}, 10)
 	service.StartedAt = time.Now()
+	service.Version = version
+	service.GitSHA = gitsha
```
Comment (jbyers19) [inline main.go:96]: Are these getting updated anywhere else? Or do they remain hard-coded to `"edge"` and `"none"`?

Comment (warunicorn19) [reply main.go:96]: I think these are hardcoded, I see the same being done on other adapters. @Revolyssup might be able to explain better.

Comment (leecalcote) [reply main.go:96]: Hard coded in main.go, but dynamically injected at build and release time.

**Review by leecalcote — APPROVED** [review]

**Review by jbyers19 — APPROVED** [review]
